name: Build Windows
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools" -y
    - name: Configure
      run: cmake -B build -DENABLE_IPC=OFF -DBUILD_TESTS=OFF
    - name: Build
      run: cmake --build build --config Release -j4
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: shivrai-hon-windows
        path: |
          build/bin/Release/bitcoind.exe
          build/bin/Release/bitcoin-cli.exe
          build/bin/Release/bitcoin-qt.exe
